<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="5.10.3" />
        <PackageReference Include="nunit" Version="3.12.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0010" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Razensoft.Psd\Razensoft.Psd.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="files\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
</ItemGroup>

</Project>
